# Generated by Django 5.1.2 on 2024-10-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_item', models.CharField(max_length=100)),
                ('order_date', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('estimated_delivery_time', models.TimeField()),
            ],
        ),
    ]
