# Generated by Django 5.1.2 on 2024-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_fname', models.CharField(max_length=100)),
                ('driver_lname', models.CharField(max_length=100)),
                ('driver_phone_number', models.IntegerField(max_length=11)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('restaurant_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
